version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongdb
    ports:
      - '27017:27017'
    volumes:
      - C:\mongodb:/data/db
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
