version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongdb
    ports:
      - '27017:27017'
    volumes:
      - C:\mongodb:/data/db
    networks:
      - rede-network

  redis:
    image: redis
    container_name: redis
    restart: always
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
    networks:
      - rede-network

#  postgres:
#      image: postgres
#      volumes:
#        - C:\postgree:/var/lib/postgresql/data
#      environment:
#        POSTGRES_DB: keycloak
#        POSTGRES_USER: keycloak
#        POSTGRES_PASSWORD: password
  
#  keycloak:
#      image: quay.io/keycloak/keycloak:latest
#      environment:
#        DB_VENDOR: POSTGRES
#        DB_ADDR: postgres
#        DB_DATABASE: keycloak
#        DB_USER: keycloak
#        DB_SCHEMA: public
#        DB_PASSWORD: password
#        KEYCLOAK_USER: admin
#        KEYCLOAK_PASSWORD: admin
#      ports:
#        - 8081:8080
#      depends_on:
#        - postgres

networks:
  rede-network:
    driver: bridge

